In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

mg_df = pd.read_csv('mackeyglass.csv')

In [186]:
#Preparação dos dados de entrada e saída.
def Entrada_Saida(K, L):
    x = np.zeros([1, K])
    y = np.zeros([1])
    for i in range(len(P)-K-L+1):
        xr = np.array([])
        for j in range(K):
            xr = np.append(xr, P[i+j])
        x = np.vstack((x, xr))
        y = np.vstack((y, P[i+K+L-1]))
    x = x[1:len(x)]
    y = y[1:len(y)]
    return(x, y)

def Transforma_Entrada(x, V):
    XX_linha = np.zeros([len(x), 1])
    for v in range(V):
        wk = np.random.uniform(-2, 2, 10)
        X_linha = []    
        for i in range(len(x)):
            x_r = x[i, :]
            x_linha = np.tanh(np.dot(wk, x_r)) 
            X_linha.append(x_linha)      
        X_linha = np.reshape(X_linha, (len(X_linha), 1))
        XX_linha = np.hstack((XX_linha, X_linha))
    XX_linha = XX_linha[:, 1:len(XX_linha[0])]
    return XX_linha 


P = mg_df.p.values

K = 10
L = 7
(x, y) = Entrada_Saida(K, L)

ranw = 21

x_linhas = np.zeros([len(x), 1])
for V in range(1, ranw, 1):  
    x_linha = Transforma_Entrada(x, V*10)      
    x_linhas = np.hstack((x_linhas, x_linha))
    print(V)
    
x_linhas = x_linhas[:, 1:len(x_linhas[0])]

#A 10 primeiras colunas de x_linhas contém os atributos transformados para V = 10, as próximas 20 linhas contém
#os atributos transformados para V = 20, e assim por diante.   

#Separação entre dados de teste e dados de validação
x_linhas_teste = x_linhas[int(0.75*len(x_linhas)):len(x_linhas)]
y_teste = y[int(0.75*len(y)):len(y)]

x_linhas_treino = x_linhas[0:int(0.75*len(x_linhas))]
y_treino = y[0:int(0.75*len(y))]

#Separação das amostras que vão ser efeitivamente utilizadas para a aproximação e as amostras para validação
x_linhas_aprox = x_linhas_treino[0:int(0.7*len(x_linhas_treino))]
y_aprox = y_treino[0:int(0.7*len(y_treino))]

x_linhas_valid =  x_linhas_treino[int(0.7*len(x_linhas_treino)):len(x_linhas_treino)]
y_valid =  y_treino[int(0.7*len(y_treino)):len(y_treino)]

print('ok')


[[0.5198708 ]
 [0.52943927]
 [0.54063174]
 ...
 [0.99722929]
 [0.99728592]
 [0.99733269]]
[[-0.54987964]
 [-0.55770452]
 [-0.56765667]
 ...
 [-0.99825722]
 [-0.9982616 ]
 [-0.99824095]]
[[-0.08095916]
 [-0.07394605]
 [-0.06948051]
 ...
 [-0.43410333]
 [-0.41729579]
 [-0.41407999]]
[[0.20857739]
 [0.22327331]
 [0.2356219 ]
 ...
 [0.76690878]
 [0.75636181]
 [0.73091522]]
[[0.55354067]
 [0.5666873 ]
 [0.57961699]
 ...
 [0.99696529]
 [0.99662873]
 [0.99595408]]
[[-0.18148115]
 [-0.18060999]
 [-0.18290228]
 ...
 [-0.86977075]
 [-0.88320415]
 [-0.90151699]]
[[-0.79774695]
 [-0.80808431]
 [-0.81882556]
 ...
 [-0.99998906]
 [-0.999989  ]
 [-0.99998807]]
[[0.43460452]
 [0.44499863]
 [0.45645363]
 ...
 [0.99111847]
 [0.9916484 ]
 [0.99188008]]
[[-0.4455415 ]
 [-0.45019883]
 [-0.45722895]
 ...
 [-0.99083559]
 [-0.9906554 ]
 [-0.9903314 ]]
[[0.75367865]
 [0.76477124]
 [0.77677252]
 ...
 [0.99997671]
 [0.99997922]
 [0.99998097]]
[[-0.38741718]
 [-0.39450811]
 [-0.40239469]
 ...
 [-0.9700515 ]
 [-0.

[[0.51717161]
 [0.53184686]
 [0.54656179]
 ...
 [0.99692249]
 [0.99707251]
 [0.99712697]]
[[0.60069317]
 [0.61572432]
 [0.63046834]
 ...
 [0.99903288]
 [0.99903935]
 [0.99897649]]
[[0.61882001]
 [0.62911402]
 [0.64129648]
 ...
 [0.99967013]
 [0.99972273]
 [0.9997651 ]]
[[-0.95609243]
 [-0.96052146]
 [-0.96481078]
 ...
 [-1.        ]
 [-1.        ]
 [-1.        ]]
[[-0.13833578]
 [-0.13417971]
 [-0.13328901]
 ...
 [-0.77115814]
 [-0.78642685]
 [-0.80938558]]
[[0.50886405]
 [0.5256593 ]
 [0.54186941]
 ...
 [0.99656212]
 [0.99678091]
 [0.99682502]]
[[-0.6514406 ]
 [-0.66329804]
 [-0.67634663]
 ...
 [-0.99977717]
 [-0.99980168]
 [-0.999818  ]]
[[0.23124625]
 [0.23919383]
 [0.24727559]
 ...
 [0.8707312 ]
 [0.87423955]
 [0.87743815]]
[[-0.84757635]
 [-0.85607578]
 [-0.86555503]
 ...
 [-0.99999935]
 [-0.9999995 ]
 [-0.99999962]]
[[-0.08645312]
 [-0.09573866]
 [-0.10258324]
 ...
 [-0.23242049]
 [-0.18932028]
 [-0.12292141]]
[[0.77660508]
 [0.78738938]
 [0.79895447]
 ...
 [0.99998691]
 [0.99998

[[0.18997071]
 [0.20451594]
 [0.21572354]
 ...
 [0.60125517]
 [0.55271589]
 [0.46624011]]
[[-0.31468602]
 [-0.3146094 ]
 [-0.31851606]
 ...
 [-0.97367099]
 [-0.97661371]
 [-0.98009359]]
[[0.94339271]
 [0.94874905]
 [0.95404971]
 ...
 [1.        ]
 [1.        ]
 [1.        ]]
[[0.84194301]
 [0.85311263]
 [0.8641088 ]
 ...
 [0.99999847]
 [0.99999868]
 [0.99999878]]
[[-0.11378372]
 [-0.11972261]
 [-0.12578887]
 ...
 [-0.65863986]
 [-0.68653989]
 [-0.7145106 ]]
[[-0.47789173]
 [-0.49548746]
 [-0.51191875]
 ...
 [-0.99388596]
 [-0.9942361 ]
 [-0.99424746]]
[[0.3384903 ]
 [0.35738487]
 [0.3734312 ]
 ...
 [0.9417979 ]
 [0.93990581]
 [0.93242497]]
[[0.20554571]
 [0.20168161]
 [0.2025479 ]
 ...
 [0.93644756]
 [0.94982998]
 [0.96356921]]
[[0.47836529]
 [0.48536044]
 [0.49530892]
 ...
 [0.99708225]
 [0.99751031]
 [0.99796717]]
[[0.50727697]
 [0.52356951]
 [0.53873408]
 ...
 [0.99408804]
 [0.99363416]
 [0.9925329 ]]
[[0.25821665]
 [0.26892888]
 [0.27973657]
 ...
 [0.9296246 ]
 [0.93801097]
 [0.944

[[-0.32498303]
 [-0.33786499]
 [-0.35050545]
 ...
 [-0.95756726]
 [-0.95886497]
 [-0.95939127]]
[[0.79035727]
 [0.80016138]
 [0.81108429]
 ...
 [0.99999284]
 [0.99999379]
 [0.99999458]]
[[0.27706338]
 [0.28828932]
 [0.29877681]
 ...
 [0.9037749 ]
 [0.90168298]
 [0.89617496]]
[[-0.0981183 ]
 [-0.09217005]
 [-0.08908452]
 ...
 [-0.56848277]
 [-0.56458164]
 [-0.57177839]]
[[-0.47460939]
 [-0.4881001 ]
 [-0.50103155]
 ...
 [-0.99054392]
 [-0.98978882]
 [-0.98807853]]
[[0.05859058]
 [0.06685424]
 [0.07378504]
 ...
 [0.36071661]
 [0.38764999]
 [0.40480792]]
[[0.15775377]
 [0.16170445]
 [0.16606529]
 ...
 [0.68939272]
 [0.68102095]
 [0.67064538]]
[[0.93551842]
 [0.94123258]
 [0.94691475]
 ...
 [0.99999999]
 [0.99999999]
 [0.99999999]]
[[0.81128983]
 [0.82226272]
 [0.83334481]
 ...
 [0.99999326]
 [0.99999336]
 [0.99999288]]
[[0.00084577]
 [0.00130631]
 [0.00233404]
 ...
 [0.17469153]
 [0.21726426]
 [0.26710461]]
[[0.31782036]
 [0.32546161]
 [0.33278027]
 ...
 [0.90719428]
 [0.89059643]
 [0.863

[[0.68099726]
 [0.69526044]
 [0.71032524]
 ...
 [0.99992009]
 [0.99993772]
 [0.99995182]]
[[-0.82409563]
 [-0.83367351]
 [-0.84383469]
 ...
 [-0.99999637]
 [-0.9999965 ]
 [-0.99999644]]
[[-0.33187376]
 [-0.33723124]
 [-0.34529369]
 ...
 [-0.98013255]
 [-0.98344276]
 [-0.98664011]]
[[-0.8840203 ]
 [-0.89241739]
 [-0.90079051]
 ...
 [-0.99999962]
 [-0.99999962]
 [-0.99999958]]
[[-0.6917947 ]
 [-0.70302284]
 [-0.71526996]
 ...
 [-0.99988104]
 [-0.99988938]
 [-0.99989247]]
[[-0.46703445]
 [-0.47935243]
 [-0.49160418]
 ...
 [-0.99068265]
 [-0.99020202]
 [-0.989289  ]]
[[-0.55734907]
 [-0.56883974]
 [-0.58167711]
 ...
 [-0.9987901 ]
 [-0.99891898]
 [-0.99902643]]
[[0.85080783]
 [0.86017493]
 [0.86990283]
 ...
 [0.99999887]
 [0.99999897]
 [0.999999  ]]
[[0.18068753]
 [0.18787924]
 [0.19570752]
 ...
 [0.83843594]
 [0.85464172]
 [0.872726  ]]
[[-0.81011864]
 [-0.82048602]
 [-0.83110049]
 ...
 [-0.99999185]
 [-0.99999154]
 [-0.9999904 ]]
[[-0.46789697]
 [-0.47829504]
 [-0.48972427]
 ...
 [-0.993

[[-0.3704553 ]
 [-0.38540479]
 [-0.39877788]
 ...
 [-0.95906956]
 [-0.95566188]
 [-0.94835346]]
[[-0.34832974]
 [-0.36399652]
 [-0.37924285]
 ...
 [-0.97765489]
 [-0.98096066]
 [-0.98380744]]
[[0.42441794]
 [0.43665513]
 [0.44852534]
 ...
 [0.98297039]
 [0.98215814]
 [0.97989655]]
[[0.01657641]
 [0.0154583 ]
 [0.01557518]
 ...
 [0.29717121]
 [0.34493456]
 [0.40407194]]
[[-0.44385907]
 [-0.45553462]
 [-0.46811319]
 ...
 [-0.99236857]
 [-0.99285115]
 [-0.99326101]]
[[0.1164665 ]
 [0.12351607]
 [0.12861468]
 ...
 [0.29111251]
 [0.21142425]
 [0.09653755]]
[[0.19653218]
 [0.20140325]
 [0.20791096]
 ...
 [0.88351864]
 [0.89762808]
 [0.91236162]]
[[0.48993259]
 [0.5025086 ]
 [0.51574033]
 ...
 [0.99572977]
 [0.99597774]
 [0.9961299 ]]
[[0.5938274 ]
 [0.61156881]
 [0.62779013]
 ...
 [0.99839537]
 [0.99827752]
 [0.99795772]]
[[-0.93994858]
 [-0.94605642]
 [-0.95185599]
 ...
 [-0.99999999]
 [-1.        ]
 [-1.        ]]
[[0.77679032]
 [0.79079939]
 [0.80445904]
 ...
 [0.99998574]
 [0.99998726]
 

[[-0.12928516]
 [-0.13699434]
 [-0.14394114]
 ...
 [-0.59585182]
 [-0.5940847 ]
 [-0.58899895]]
[[0.61179978]
 [0.62628112]
 [0.64001079]
 ...
 [0.99869445]
 [0.99853122]
 [0.99816504]]
[[0.8353756 ]
 [0.84481244]
 [0.8547315 ]
 ...
 [0.9999979 ]
 [0.99999812]
 [0.99999822]]
[[-0.26370947]
 [-0.27018501]
 [-0.27835924]
 ...
 [-0.94366743]
 [-0.95039392]
 [-0.95733612]]
[[0.37302589]
 [0.38153246]
 [0.39140643]
 ...
 [0.98216548]
 [0.9838947 ]
 [0.98552782]]
[[-0.27268244]
 [-0.27546239]
 [-0.2810891 ]
 ...
 [-0.95659509]
 [-0.96315127]
 [-0.97013484]]
[[0.63232092]
 [0.64462   ]
 [0.65821725]
 ...
 [0.99969738]
 [0.99973159]
 [0.99976456]]
[[-0.95544918]
 [-0.95941881]
 [-0.96359738]
 ...
 [-1.        ]
 [-1.        ]
 [-1.        ]]
[[-0.30840763]
 [-0.31594262]
 [-0.32423881]
 ...
 [-0.94705758]
 [-0.94801132]
 [-0.94755834]]
[[-0.44947414]
 [-0.4623301 ]
 [-0.47562461]
 ...
 [-0.99175655]
 [-0.9919618 ]
 [-0.99203247]]
[[-0.49817082]
 [-0.52035737]
 [-0.53981529]
 ...
 [-0.99399019]

[[0.59222373]
 [0.60104344]
 [0.61210754]
 ...
 [0.99937098]
 [0.99943318]
 [0.99949808]]
[[-0.72404896]
 [-0.74117976]
 [-0.75712175]
 ...
 [-0.99993225]
 [-0.9999386 ]
 [-0.99993892]]
[[0.42039833]
 [0.43105773]
 [0.4420627 ]
 ...
 [0.98270949]
 [0.98131788]
 [0.97899822]]
[[-0.24906406]
 [-0.25642547]
 [-0.26408072]
 ...
 [-0.89167989]
 [-0.89390951]
 [-0.8941722 ]]
[[-0.40422057]
 [-0.41155836]
 [-0.42072461]
 ...
 [-0.98675598]
 [-0.98722824]
 [-0.98758752]]
[[-0.56529154]
 [-0.57450388]
 [-0.58603285]
 ...
 [-0.9991524 ]
 [-0.99926385]
 [-0.99936558]]
[[0.73103612]
 [0.74567629]
 [0.76005247]
 ...
 [0.99994999]
 [0.99995479]
 [0.99995638]]
[[0.19288939]
 [0.18857329]
 [0.1892251 ]
 ...
 [0.92881764]
 [0.94297201]
 [0.9582155 ]]
[[-0.63310872]
 [-0.64646423]
 [-0.6603951 ]
 ...
 [-0.99961655]
 [-0.99964775]
 [-0.99966293]]
[[-0.63520754]
 [-0.64504589]
 [-0.65700598]
 ...
 [-0.99975695]
 [-0.99979131]
 [-0.99982177]]
[[0.8503099 ]
 [0.85822018]
 [0.86712617]
 ...
 [0.99999917]
 [0

[[-0.58797182]
 [-0.60380833]
 [-0.61862512]
 ...
 [-0.99825411]
 [-0.9981185 ]
 [-0.99774731]]
[[-0.60016217]
 [-0.6134877 ]
 [-0.6276242 ]
 ...
 [-0.99942159]
 [-0.99949187]
 [-0.99953679]]
[[0.75604923]
 [0.77050564]
 [0.78460169]
 ...
 [0.99997653]
 [0.99997988]
 [0.99998144]]
[[-0.09730025]
 [-0.09066675]
 [-0.08709671]
 ...
 [-0.5934979 ]
 [-0.59885513]
 [-0.61278914]]
[[0.17595037]
 [0.17227299]
 [0.17160322]
 ...
 [0.80689479]
 [0.80905054]
 [0.81579656]]
[[-0.68501635]
 [-0.69971739]
 [-0.71451061]
 ...
 [-0.9998648 ]
 [-0.99987664]
 [-0.99988413]]
[[0.34284707]
 [0.35697959]
 [0.36987292]
 ...
 [0.95099368]
 [0.94908779]
 [0.94463696]]
[[-0.25717059]
 [-0.25887002]
 [-0.26345377]
 ...
 [-0.93568253]
 [-0.94033343]
 [-0.94746618]]
[[0.42530168]
 [0.43806998]
 [0.45125604]
 ...
 [0.99018988]
 [0.9909952 ]
 [0.99148934]]
[[-0.91242713]
 [-0.91904263]
 [-0.92590829]
 ...
 [-0.99999996]
 [-0.99999997]
 [-0.99999997]]
[[-0.19364419]
 [-0.19258464]
 [-0.19454236]
 ...
 [-0.86897066]

[[-0.25137978]
 [-0.26074302]
 [-0.27043563]
 ...
 [-0.91328287]
 [-0.91868795]
 [-0.92344529]]
[[-0.61703882]
 [-0.62779791]
 [-0.63955989]
 ...
 [-0.99924382]
 [-0.99920153]
 [-0.99911596]]
[[-0.8314578 ]
 [-0.84128687]
 [-0.85120648]
 ...
 [-0.99999538]
 [-0.99999504]
 [-0.99999407]]
[[-0.93081814]
 [-0.93635384]
 [-0.94208688]
 ...
 [-0.99999999]
 [-0.99999999]
 [-0.99999999]]
[[-0.83410061]
 [-0.84343818]
 [-0.85365689]
 ...
 [-0.99999885]
 [-0.99999912]
 [-0.99999932]]
[[-0.43361986]
 [-0.44194709]
 [-0.45335486]
 ...
 [-0.99647346]
 [-0.99737776]
 [-0.99817336]]
[[0.76563633]
 [0.77944398]
 [0.79283939]
 ...
 [0.99997312]
 [0.99997385]
 [0.99997256]]
[[0.64084705]
 [0.65745297]
 [0.67295997]
 ...
 [0.99938861]
 [0.99936449]
 [0.99928162]]
[[0.77326576]
 [0.78691076]
 [0.80015054]
 ...
 [0.99997794]
 [0.99997825]
 [0.99997667]]
[[-0.68916602]
 [-0.70277779]
 [-0.71620287]
 ...
 [-0.99977936]
 [-0.99976627]
 [-0.99973062]]
[[0.22232442]
 [0.23787215]
 [0.25108677]
 ...
 [0.8233631

[[-0.30078798]
 [-0.30399539]
 [-0.3089571 ]
 ...
 [-0.93656028]
 [-0.9340763 ]
 [-0.93082832]]
[[-0.07036727]
 [-0.06268328]
 [-0.05907997]
 ...
 [-0.67033931]
 [-0.7153646 ]
 [-0.77160926]]
[[-0.29205532]
 [-0.29949557]
 [-0.30844071]
 ...
 [-0.95868272]
 [-0.96402041]
 [-0.96915419]]
[[-0.16281184]
 [-0.17211716]
 [-0.18010257]
 ...
 [-0.65043296]
 [-0.63568881]
 [-0.60897738]]
[[0.32712013]
 [0.32881314]
 [0.33387345]
 ...
 [0.97610392]
 [0.97904186]
 [0.98221977]]
[[-0.01323737]
 [-0.00999008]
 [-0.00796625]
 ...
 [-0.14661451]
 [-0.15537291]
 [-0.17066346]]
[[-0.85389763]
 [-0.86424609]
 [-0.87442535]
 ...
 [-0.99999874]
 [-0.99999881]
 [-0.99999879]]
[[0.67227134]
 [0.68839558]
 [0.70353666]
 ...
 [0.9996685 ]
 [0.99965179]
 [0.99959624]]
[[0.75274295]
 [0.76673593]
 [0.7803394 ]
 ...
 [0.99996511]
 [0.99996723]
 [0.99996632]]
[[0.30468571]
 [0.30938907]
 [0.31580657]
 ...
 [0.94954473]
 [0.950717  ]
 [0.9524416 ]]
[[0.75252516]
 [0.7623917 ]
 [0.77329049]
 ...
 [0.99996493]
 [0

[[-0.56396156]
 [-0.5790648 ]
 [-0.59403414]
 ...
 [-0.99842416]
 [-0.99848222]
 [-0.99845741]]
[[0.54961304]
 [0.56220474]
 [0.57608622]
 ...
 [0.99890183]
 [0.99907838]
 [0.99921988]]
[[-0.79701221]
 [-0.80753457]
 [-0.81852918]
 ...
 [-0.99998963]
 [-0.99998956]
 [-0.99998882]]
[[-0.1331138 ]
 [-0.1394539 ]
 [-0.14495032]
 ...
 [-0.52261538]
 [-0.49147023]
 [-0.44848653]]
[[-0.08054225]
 [-0.09330325]
 [-0.10279291]
 ...
 [-0.20649734]
 [-0.17248728]
 [-0.11519567]]
[[0.56108145]
 [0.57462201]
 [0.58946781]
 ...
 [0.99926655]
 [0.99942509]
 [0.9995537 ]]
[[-0.03919426]
 [-0.02903994]
 [-0.02326644]
 ...
 [-0.54933131]
 [-0.5994544 ]
 [-0.66683177]]
[[-0.46717724]
 [-0.47911195]
 [-0.49206251]
 ...
 [-0.99490221]
 [-0.9953238 ]
 [-0.99566936]]
[[0.01538333]
 [0.0161404 ]
 [0.01690951]
 ...
 [0.08963693]
 [0.08781126]
 [0.08068555]]
[[0.13875036]
 [0.14622555]
 [0.1522944 ]
 ...
 [0.51434243]
 [0.48324957]
 [0.43297785]]
[[-0.54698783]
 [-0.55937837]
 [-0.57267598]
 ...
 [-0.99821976]

[[-0.50913878]
 [-0.52320831]
 [-0.53622408]
 ...
 [-0.99252593]
 [-0.99148644]
 [-0.989217  ]]
[[0.19223429]
 [0.19626958]
 [0.20170467]
 ...
 [0.85839378]
 [0.87171843]
 [0.88513131]]
[[-0.77594384]
 [-0.78689316]
 [-0.79822841]
 ...
 [-0.99997815]
 [-0.99997756]
 [-0.99997496]]
[[-0.3847763 ]
 [-0.39472492]
 [-0.40431913]
 ...
 [-0.96439622]
 [-0.9601676 ]
 [-0.95194409]]
[[-0.59838768]
 [-0.60750523]
 [-0.61825198]
 ...
 [-0.99913873]
 [-0.9991382 ]
 [-0.99911293]]
[[-0.60885358]
 [-0.61818651]
 [-0.62965256]
 ...
 [-0.99954117]
 [-0.99958907]
 [-0.99963669]]
[[-0.213087  ]
 [-0.21341237]
 [-0.21588341]
 ...
 [-0.86104098]
 [-0.86348504]
 [-0.86713069]]
[[-0.34418764]
 [-0.35550802]
 [-0.36699597]
 ...
 [-0.9668429 ]
 [-0.9681594 ]
 [-0.96897863]]
[[-0.32560832]
 [-0.33027635]
 [-0.33674171]
 ...
 [-0.96062501]
 [-0.96149415]
 [-0.96234496]]
[[0.06636072]
 [0.0686609 ]
 [0.07159561]
 ...
 [0.43785829]
 [0.45171739]
 [0.47841029]]
[[0.65204909]
 [0.66419992]
 [0.67712675]
 ...
 [0.9

[[-0.37092446]
 [-0.38570533]
 [-0.39892164]
 ...
 [-0.9574716 ]
 [-0.95330488]
 [-0.94516712]]
[[-0.68879415]
 [-0.70064735]
 [-0.71314884]
 ...
 [-0.99983824]
 [-0.9998398 ]
 [-0.99983313]]
[[0.41902108]
 [0.43586955]
 [0.45068135]
 ...
 [0.97468825]
 [0.97167756]
 [0.96530378]]
[[-0.48067029]
 [-0.48964582]
 [-0.50163758]
 ...
 [-0.99800491]
 [-0.99845209]
 [-0.99887963]]
[[0.61756741]
 [0.63138126]
 [0.64569752]
 ...
 [0.99951081]
 [0.99955596]
 [0.99958243]]
[[0.65134126]
 [0.65936866]
 [0.66995963]
 ...
 [0.99982407]
 [0.99984851]
 [0.99987085]]
[[-0.54968797]
 [-0.55919543]
 [-0.57012751]
 ...
 [-0.99800749]
 [-0.99799626]
 [-0.99792572]]
[[-0.49785094]
 [-0.50637309]
 [-0.51728834]
 ...
 [-0.99769927]
 [-0.998066  ]
 [-0.99840261]]
[[-0.79834424]
 [-0.81245117]
 [-0.82558708]
 ...
 [-0.99998753]
 [-0.99998765]
 [-0.99998647]]
[[-0.41503941]
 [-0.42152157]
 [-0.43019831]
 ...
 [-0.99043973]
 [-0.99136125]
 [-0.99211387]]
[[0.18787259]
 [0.19388549]
 [0.20056487]
 ...
 [0.8267503

[[0.57139617]
 [0.58483957]
 [0.5987553 ]
 ...
 [0.99870648]
 [0.99875839]
 [0.99877177]]
[[-0.92812864]
 [-0.93581162]
 [-0.94280686]
 ...
 [-0.99999998]
 [-0.99999998]
 [-0.99999998]]
[[0.85879103]
 [0.8664439 ]
 [0.87486131]
 ...
 [0.99999909]
 [0.99999913]
 [0.99999912]]
[[-0.17322782]
 [-0.18146506]
 [-0.18842573]
 ...
 [-0.6286049 ]
 [-0.59298099]
 [-0.53846386]]
[[-0.62894649]
 [-0.64140006]
 [-0.654343  ]
 ...
 [-0.99945433]
 [-0.99946184]
 [-0.99943532]]
[[-0.05386333]
 [-0.04289113]
 [-0.03679879]
 ...
 [-0.60958402]
 [-0.65019397]
 [-0.70979483]]
[[0.22458806]
 [0.22242266]
 [0.22353484]
 ...
 [0.89978866]
 [0.90486556]
 [0.91269735]]
[[0.58775197]
 [0.59647239]
 [0.60764275]
 ...
 [0.9994539 ]
 [0.99953888]
 [0.99961231]]
[[-0.56590639]
 [-0.58476308]
 [-0.60180111]
 ...
 [-0.99757604]
 [-0.9974364 ]
 [-0.99697545]]
[[0.45302491]
 [0.46782692]
 [0.48214089]
 ...
 [0.99086098]
 [0.9910369 ]
 [0.99073292]]
[[-0.78896682]
 [-0.80015375]
 [-0.81188583]
 ...
 [-0.99999201]
 [-0.

[[-0.67547316]
 [-0.68635497]
 [-0.6986761 ]
 ...
 [-0.99986595]
 [-0.99988098]
 [-0.99989307]]
[[0.3392627 ]
 [0.34553512]
 [0.35307637]
 ...
 [0.96419843]
 [0.96473267]
 [0.96415727]]
[[0.91850188]
 [0.92616152]
 [0.93334701]
 ...
 [0.99999995]
 [0.99999995]
 [0.99999995]]
[[0.18788605]
 [0.18870414]
 [0.19126617]
 ...
 [0.81983754]
 [0.82549004]
 [0.83179212]]
[[0.61020031]
 [0.62084713]
 [0.63294311]
 ...
 [0.99943466]
 [0.9994683 ]
 [0.99949134]]
[[0.80098417]
 [0.80978272]
 [0.81969312]
 ...
 [0.99999265]
 [0.9999929 ]
 [0.99999278]]
[[-0.74089539]
 [-0.75475952]
 [-0.76863216]
 ...
 [-0.99996374]
 [-0.99996772]
 [-0.99997001]]
[[-0.27073027]
 [-0.27792285]
 [-0.28612156]
 ...
 [-0.93499944]
 [-0.94025535]
 [-0.94480793]]
[[-0.74890235]
 [-0.75991786]
 [-0.77176082]
 ...
 [-0.99996935]
 [-0.99997162]
 [-0.99997249]]
[[-0.54641678]
 [-0.55630527]
 [-0.5685135 ]
 ...
 [-0.99893445]
 [-0.99909221]
 [-0.9992536 ]]
[[-0.63758281]
 [-0.65372292]
 [-0.6695608 ]
 ...
 [-0.99961068]
 [-0.

[[0.2899356 ]
 [0.30678956]
 [0.32190698]
 ...
 [0.9354329 ]
 [0.94064455]
 [0.94380324]]
[[-0.85848407]
 [-0.86692596]
 [-0.87588841]
 ...
 [-0.99999919]
 [-0.99999927]
 [-0.9999993 ]]
[[0.79105479]
 [0.80432838]
 [0.81716498]
 ...
 [0.99998805]
 [0.99998871]
 [0.99998828]]
[[-0.00835201]
 [-0.00178134]
 [ 0.00214229]
 ...
 [-0.26428639]
 [-0.2976828 ]
 [-0.35454689]]
[[0.0275277 ]
 [0.02989733]
 [0.03347893]
 ...
 [0.49454942]
 [0.5699522 ]
 [0.65460688]]
[[0.62584024]
 [0.64386824]
 [0.66081575]
 ...
 [0.99943829]
 [0.99947032]
 [0.99947007]]
[[-0.2254531 ]
 [-0.22936239]
 [-0.23427449]
 ...
 [-0.86169929]
 [-0.86277841]
 [-0.86218025]]
[[0.08652405]
 [0.08958219]
 [0.09217956]
 ...
 [0.31822968]
 [0.28043594]
 [0.23457333]]
[[0.73526807]
 [0.74597125]
 [0.75798256]
 ...
 [0.99996909]
 [0.99997334]
 [0.99997642]]
[[-0.89784582]
 [-0.90659842]
 [-0.91500023]
 ...
 [-0.99999986]
 [-0.99999987]
 [-0.99999987]]
[[0.61752624]
 [0.62347082]
 [0.63243293]
 ...
 [0.99956351]
 [0.99958207]
 

[[0.80424688]
 [0.81364516]
 [0.82396592]
 ...
 [0.99999405]
 [0.99999452]
 [0.99999469]]
[[0.43683285]
 [0.45378649]
 [0.46927679]
 ...
 [0.98442812]
 [0.9833421 ]
 [0.98098285]]
[[0.88692122]
 [0.89424529]
 [0.90214809]
 ...
 [0.99999985]
 [0.99999987]
 [0.99999989]]
[[0.19662244]
 [0.20308732]
 [0.21056009]
 ...
 [0.87214311]
 [0.88603978]
 [0.89966476]]
[[-0.37987363]
 [-0.39270667]
 [-0.40560969]
 ...
 [-0.97874114]
 [-0.97936842]
 [-0.97972286]]
[[0.51926837]
 [0.52829453]
 [0.53900909]
 ...
 [0.99732416]
 [0.99744852]
 [0.997544  ]]
[[0.63273144]
 [0.64175987]
 [0.65306264]
 ...
 [0.99971864]
 [0.99974942]
 [0.99978143]]
[[-0.88113995]
 [-0.88859444]
 [-0.89678318]
 ...
 [-0.99999982]
 [-0.99999986]
 [-0.99999988]]
[[-0.56768452]
 [-0.5746926 ]
 [-0.58490631]
 ...
 [-0.99936672]
 [-0.99948095]
 [-0.99958831]]
[[0.08870988]
 [0.09574795]
 [0.10089157]
 ...
 [0.24893705]
 [0.20387023]
 [0.12977133]]
[[0.23000687]
 [0.23958301]
 [0.24783687]
 ...
 [0.79238143]
 [0.77662648]
 [0.747

[[0.32366601]
 [0.32957939]
 [0.33731966]
 ...
 [0.96789936]
 [0.97066395]
 [0.97330052]]
[[-0.49868958]
 [-0.50758923]
 [-0.51829114]
 ...
 [-0.99664787]
 [-0.99685302]
 [-0.99699006]]
[[-0.88516828]
 [-0.8924426 ]
 [-0.90036172]
 ...
 [-0.99999983]
 [-0.99999986]
 [-0.99999988]]
[[-0.79553263]
 [-0.80473233]
 [-0.81491359]
 ...
 [-0.99999064]
 [-0.99999086]
 [-0.99999063]]
[[0.83377382]
 [0.84378047]
 [0.85387699]
 ...
 [0.99999668]
 [0.99999673]
 [0.99999645]]
[[-0.69434705]
 [-0.7055832 ]
 [-0.717984  ]
 ...
 [-0.99989917]
 [-0.99990837]
 [-0.99991469]]
[[ 0.04955055]
 [ 0.05961986]
 [ 0.066071  ]
 ...
 [-0.1339671 ]
 [-0.2143542 ]
 [-0.32613109]]
[[0.64241923]
 [0.65130704]
 [0.66200962]
 ...
 [0.99965196]
 [0.99965851]
 [0.99965992]]
[[-0.57529599]
 [-0.58631687]
 [-0.59912358]
 ...
 [-0.99930153]
 [-0.99941386]
 [-0.99951123]]
[[-0.75915157]
 [-0.77176198]
 [-0.78492359]
 ...
 [-0.99998465]
 [-0.9999875 ]
 [-0.99998958]]
[[-0.07157811]
 [-0.07569505]
 [-0.07961932]
 ...
 [-0.430

[[-0.67505265]
 [-0.69089205]
 [-0.70648377]
 ...
 [-0.99984227]
 [-0.99986065]
 [-0.99986963]]
[[0.88976069]
 [0.89842749]
 [0.90694812]
 ...
 [0.99999979]
 [0.99999981]
 [0.99999981]]
[[0.62608674]
 [0.6401056 ]
 [0.65413808]
 ...
 [0.99939423]
 [0.99939965]
 [0.99936845]]
[[-0.64350982]
 [-0.65609965]
 [-0.66907276]
 ...
 [-0.99952546]
 [-0.99950635]
 [-0.99945223]]
[[-0.9146299 ]
 [-0.92068493]
 [-0.92712654]
 ...
 [-0.99999996]
 [-0.99999997]
 [-0.99999997]]
[[0.93964236]
 [0.94502979]
 [0.95033281]
 ...
 [0.99999999]
 [0.99999999]
 [0.99999999]]
[[0.00332953]
 [0.00891223]
 [0.01372713]
 ...
 [0.17419381]
 [0.22862006]
 [0.28338797]]
[[-0.12382023]
 [-0.1258447 ]
 [-0.12878125]
 ...
 [-0.62257933]
 [-0.62280233]
 [-0.62777841]]
[[0.62863186]
 [0.64303491]
 [0.65796281]
 ...
 [0.99966187]
 [0.99970669]
 [0.99974054]]
[[0.26462   ]
 [0.26492101]
 [0.26848144]
 ...
 [0.94896941]
 [0.95515635]
 [0.96205921]]
[[-0.78136084]
 [-0.79573305]
 [-0.80929014]
 ...
 [-0.9999808 ]
 [-0.999981

[[0.8099508 ]
 [0.82348013]
 [0.83652235]
 ...
 [0.99999605]
 [0.99999683]
 [0.99999728]]
[[0.12290214]
 [0.13285096]
 [0.14097332]
 ...
 [0.49410704]
 [0.47610819]
 [0.44458292]]
[[0.36434206]
 [0.36588026]
 [0.37166053]
 ...
 [0.98864642]
 [0.99051591]
 [0.99260465]]
[[-0.85947873]
 [-0.86803677]
 [-0.87728235]
 ...
 [-0.9999995 ]
 [-0.9999996 ]
 [-0.99999967]]
[[0.77506911]
 [0.78712215]
 [0.79917083]
 ...
 [0.99997766]
 [0.99997781]
 [0.9999762 ]]
[[-0.09924998]
 [-0.10580166]
 [-0.11201106]
 ...
 [-0.56194118]
 [-0.58067826]
 [-0.60019024]]
[[0.73145911]
 [0.74669239]
 [0.76104421]
 ...
 [0.99992243]
 [0.99992261]
 [0.9999135 ]]
[[0.77423679]
 [0.78471781]
 [0.79590681]
 ...
 [0.99998334]
 [0.99998446]
 [0.9999846 ]]
[[-0.75657447]
 [-0.76820572]
 [-0.78022293]
 ...
 [-0.9999669 ]
 [-0.99996727]
 [-0.99996585]]
[[-0.80113883]
 [-0.81008193]
 [-0.82033747]
 ...
 [-0.99999501]
 [-0.99999564]
 [-0.99999615]]
[[-0.81855798]
 [-0.83064568]
 [-0.84229591]
 ...
 [-0.99999401]
 [-0.999994

[[-0.6246156 ]
 [-0.63973263]
 [-0.65417354]
 ...
 [-0.99909243]
 [-0.99900148]
 [-0.9987976 ]]
[[-0.75329756]
 [-0.76372073]
 [-0.77522849]
 ...
 [-0.99997528]
 [-0.99997739]
 [-0.99997864]]
[[0.26252567]
 [0.26767281]
 [0.27379948]
 ...
 [0.90144814]
 [0.89909015]
 [0.89502103]]
[[-0.69187579]
 [-0.70026086]
 [-0.71078339]
 ...
 [-0.99990752]
 [-0.99991642]
 [-0.9999236 ]]
[[0.47117941]
 [0.4758463 ]
 [0.48373287]
 ...
 [0.99609551]
 [0.99648498]
 [0.9969286 ]]
[[0.31279702]
 [0.3147129 ]
 [0.31862194]
 ...
 [0.93808491]
 [0.93253566]
 [0.92570487]]
[[0.75502011]
 [0.76875109]
 [0.78241858]
 ...
 [0.99997564]
 [0.99997857]
 [0.99997988]]
[[-0.82837319]
 [-0.84007732]
 [-0.8512516 ]
 ...
 [-0.99999493]
 [-0.99999477]
 [-0.99999393]]
[[-0.53599864]
 [-0.54839461]
 [-0.5610295 ]
 ...
 [-0.99684167]
 [-0.99671065]
 [-0.9963821 ]]
[[-0.51437069]
 [-0.53011959]
 [-0.54487563]
 ...
 [-0.99489143]
 [-0.99462192]
 [-0.99386801]]
[[0.67302377]
 [0.68739512]
 [0.7022655 ]
 ...
 [0.99986343]
 [0

[[0.46595068]
 [0.48237005]
 [0.49857835]
 ...
 [0.99475118]
 [0.99530514]
 [0.99577048]]
[[0.07398488]
 [0.07301661]
 [0.07401999]
 ...
 [0.59923622]
 [0.63833079]
 [0.68126864]]
[[-0.39825405]
 [-0.40739594]
 [-0.41742965]
 ...
 [-0.9806724 ]
 [-0.98008185]
 [-0.97905735]]
[[0.32767019]
 [0.34159848]
 [0.35417968]
 ...
 [0.93906648]
 [0.93581037]
 [0.92791849]]
[[0.4452671 ]
 [0.45512877]
 [0.46531597]
 ...
 [0.98533092]
 [0.98349664]
 [0.98038147]]
[[-0.28316615]
 [-0.29947164]
 [-0.31292628]
 ...
 [-0.85609157]
 [-0.83732389]
 [-0.80209077]]
[[0.52375505]
 [0.53879297]
 [0.55309387]
 ...
 [0.99534957]
 [0.99494978]
 [0.99410067]]
[[-0.31483624]
 [-0.32474366]
 [-0.33495985]
 ...
 [-0.95214195]
 [-0.95375828]
 [-0.95425784]]
[[-0.59742605]
 [-0.60954212]
 [-0.62243148]
 ...
 [-0.9991433 ]
 [-0.99916727]
 [-0.9991521 ]]
[[0.40564966]
 [0.4153373 ]
 [0.42646954]
 ...
 [0.98908534]
 [0.99021134]
 [0.99129852]]
[[-0.71517042]
 [-0.72993324]
 [-0.74461632]
 ...
 [-0.99993365]
 [-0.999941

In [165]:
#Treinamento

def Calcula_Param(x, y, lamb):
    temp = np.ones((len(x), 1))
    fi = np.concatenate((temp, x), axis = 1)
    aux = np.matmul(fi.T, fi) 
    z = np.zeros(len(aux)-1)
    I = np.eye(len(aux)-1)
    I_linha = np.vstack((z, I)) 
    z = np.zeros(len(I_linha))
    z = np.reshape(z, [len(z), 1])
    I_linha = np.hstack((z, I_linha))                                                                                                                                            
    aux = aux + lamb*I_linha
    FI = np.matmul(np.linalg.inv(aux), fi.T)
    w = np.matmul(FI, y)
    return (w)
    
indice_antes = 0
indice_depois = 10

W = np.zeros([1001, 1])
for V in range (1, ranw, 1):
        
    x_linha_aprox_desempacotado = x_linhas_aprox[:, indice_antes : indice_depois]
    
    indice_antes = indice_antes + 10*V
    indice_depois = indice_depois + 10*(V+1)
    
    
    w = Calcula_Param(x_linha_aprox_desempacotado, y_aprox, 1000)
    Completa_w = np.zeros([1001-len(w), 1])
    w = np.vstack((w, Completa_w))
    W = np.hstack((W,w))
    
print('ok')
        
        


ok


In [183]:
#Validação
def Desempacota_Parametros(V, W):
    w = W[:, V]
    w = w[0:10*V+1]
    w = np.reshape(w, (len(w), 1))
    return w

def Calcula_Saidas(x_valid, w, K, L):
    Y = []
    for i in range(len(x_valid)-K-L+1):
        x = np.array([1])
        x = np.append(x, x_valid[i])        
        x = np.reshape(x, (len(x), 1))
        y_calc = np.dot(w.T,x)  
        y_calc = np.ndarray.tolist(y_calc[0])
        y_esperado = y_valid[i+K+L-1]
        Y.append((y_calc[0], y_esperado))
    return(Y)

def Calcula_RMSE(Y):
    e = 0
    for y in Y:
        y_calc, y_esp = y
        e += (y_calc - y_esp)**2
    e = e/len(Y)
    e = e**(1/2)
    return e

L = 7
K = 10

indice_antes = 0
indice_depois = 10

E = []
Vs = []

for V in range (1, len(W[0])):
    
    w = Desempacota_Parametros(V, W)
    
    print(len(w))
    
    x_linha_valid_desempacotado = x_linhas_valid[:, indice_antes : indice_depois]

    indice_antes = indice_antes + 10*V
    indice_depois = indice_depois + 10*(V+1)
     
    Y = Calcula_Saidas(x_linha_valid_desempacotado, w, K, L)
    E.append(Calcula_RMSE(Y))
    Vs.append(10*V)

    
    
fig, ax = plt.subplots()
ax.stem(Vs, E)
ax.set_ylabel('RMSE')
ax.set_xlabel('V')
plt.show()


11
21
31
41
51
61
71
81
91
101
111
121
131
141
151
161
171
181
191
201


In [167]:
min(E)

array([0.27422388])

In [168]:
max(y) - min(y)

array([1.07417447])

In [171]:
min(x_linhas_aprox[0])

-0.855171937673613

In [181]:
E

[array([0.27586512]),
 array([0.27422388]),
 array([0.29125766]),
 array([0.28801177]),
 array([0.29012664]),
 array([0.30080468]),
 array([0.30515681]),
 array([0.30456035]),
 array([0.31290629]),
 array([0.31328568]),
 array([0.31667297]),
 array([0.32341445]),
 array([0.3249308]),
 array([0.31991626]),
 array([0.3275718]),
 array([0.32706479]),
 array([0.32977632]),
 array([0.33261373]),
 array([0.32698618]),
 array([0.33689627])]

In [176]:
y_calc, y_esp = Y[10]

In [177]:
y_esp

array([0.70221075])

In [180]:
(y_calc-y_esp) ** 2

array([0.02221681])

In [179]:
0.8512638001132828 - 0.70221075

0.14905305011328285

In [187]:
min(y)

array([0.29277651])

In [ ]:
ys_norm = []
for yps in y:
    y_norm =  2*(yps-min(y)) / (max(y) - min(y))
    y_norm = y_norm - 1
    ys_norm.append(y_norm)

array([1.07417447])

array([0.29277651])

In [196]:
ys_norm

[array([0.]),
 array([0.00609795]),
 array([0.01193931]),
 array([0.0175177]),
 array([0.02283026]),
 array([0.02787707]),
 array([0.03266025]),
 array([0.03724261]),
 array([0.04188417]),
 array([0.0468224]),
 array([0.05222144]),
 array([0.05818634]),
 array([0.06477543]),
 array([0.07201044]),
 array([0.07988475]),
 array([0.08837042]),
 array([0.09742386]),
 array([0.10699055]),
 array([0.11700878]),
 array([0.12741272]),
 array([0.13813481]),
 array([0.14910768]),
 array([0.16026555]),
 array([0.17154538]),
 array([0.18288765]),
 array([0.19423688]),
 array([0.20554202]),
 array([0.21675662]),
 array([0.22783877]),
 array([0.23875426]),
 array([0.24950431]),
 array([0.26014017]),
 array([0.27074601]),
 array([0.28142328]),
 array([0.29227909]),
 array([0.30341769]),
 array([0.31493467]),
 array([0.326913]),
 array([0.33942076]),
 array([0.35250997]),
 array([0.36621643]),
 array([0.38056009]),
 array([0.39554596]),
 array([0.41116535]),
 array([0.42739722]),
 array([0.44420966]),
